return if User.where(id: 1, role: User::SUPERADMIN).exists?
puts "Seeding #{Rails.env} db"

RawQuery.new("
  INSERT INTO states (id, name) VALUES
  ('AL', 'Alabama'),
  ('AK', 'Alaska'),
  ('AZ', 'Arizona'),
  ('AR', 'Arkansas'),
  ('CA', 'California'),
  ('CO', 'Colorado'),
  ('CT', 'Connecticut'),
  ('DE', 'Delaware'),
  ('FL', 'Florida'),
  ('GA', 'Georgia'),
  ('HI', 'Hawaii'),
  ('ID', 'Idaho'),
  ('IL', 'Illinois'),
  ('IN', 'Indiana'),
  ('IA', 'Iowa'),
  ('KS', 'Kansas'),
  ('KY', 'Kentucky'),
  ('LA', 'Louisiana'),
  ('ME', 'Maine'),
  ('MD', 'Maryland'),
  ('MA', 'Massachusetts'),
  ('MI', 'Michigan'),
  ('MN', 'Minnesota'),
  ('MS', 'Mississippi'),
  ('MO', 'Missouri'),
  ('MT', 'Montana'),
  ('NE', 'Nebraska'),
  ('NV', 'Nevada'),
  ('NH', 'New Hampshire'),
  ('NJ', 'New Jersey'),
  ('NM', 'New Mexico'),
  ('NY', 'New York'),
  ('NC', 'North Carolina'),
  ('ND', 'North Dakota'),
  ('OH', 'Ohio'),
  ('OK', 'Oklahoma'),
  ('OR', 'Oregon'),
  ('PA', 'Pennsylvania'),
  ('RI', 'Rhode Island'),
  ('SC', 'South Carolina'),
  ('SD', 'South Dakota'),
  ('TN', 'Tennessee'),
  ('TX', 'Texas'),
  ('UT', 'Utah'),
  ('VT', 'Vermont'),
  ('VA', 'Virginia'),
  ('WA', 'Washington'),
  ('WV', 'West Virginia'),
  ('WI', 'Wisconsin'),
  ('WY', 'Wyoming');
").run_ignore_result

RawQuery.new("
  INSERT INTO representatives (first_name, last_name, state_id, level, party) VALUES
  ('Jack', 'Reed', 'RI', 'S', 'D'),
  ('Lindsey', 'Graham', 'SC', 'S', 'R'),
  ('Richard', 'Burr', 'NC', 'S', 'R'),
  ('Pat', 'Toomey', 'PA', 'S', 'R'),
  ('Lamar', 'Alexander', 'TN', 'S', 'R'),
  ('Shelley', 'Moore Capito', 'WV', 'S', 'R'),
  ('Bob', 'Corker', 'TN', 'S', 'R'),
  ('Todd', 'C. Young', 'IN', 'S', 'R'),
  ('Pat', 'Roberts', 'KS', 'S', 'R'),
  ('Chris', 'Coons', 'DE', 'S', 'D'),
  ('Ben', 'Sasse', 'NE', 'S', 'R'),
  ('Bill', 'Cassidy', 'LA', 'S', 'R'),
  ('Gary', 'Peters', 'MI', 'S', 'D'),
  ('John', 'Neely Kennedy', 'LA', 'S', 'R'),
  ('Maggie', 'Hassan', 'NH', 'S', 'D'),
  ('Bob', 'Menendez', 'NJ', 'S', 'D'),
  ('Tammy', 'Duckworth', 'IL', 'S', 'D'),
  ('Thom', 'Tillis', 'NC', 'S', 'R'),
  ('Dick', 'Durbin', 'IL', 'S', 'D'),
  ('David', 'Perdue', 'GA', 'S', 'R'),
  ('Mark', 'Warner', 'VA', 'S', 'D'),
  ('Orrin', 'Hatch', 'UT', 'S', 'R'),
  ('Daniel', 'S. Sullivan', 'AK', 'S', 'R'),
  ('Doug', 'Jones', 'AL', 'S', 'D'),
  ('Brian', 'E. Schatz', 'HI', 'S', 'D'),
  ('Chuck', 'Schumer', 'NY', 'S', 'D'),
  ('Chuck', 'Grassley', 'IA', 'S', 'R'),
  ('Steve', 'Daines', 'MT', 'S', 'R'),
  ('Chris', 'Van Hollen', 'MD', 'S', 'D'),
  ('Michael', 'Bennet', 'CO', 'S', 'D'),
  ('Jim', 'Inhofe', 'OK', 'S', 'R'),
  ('Jerry', 'Moran', 'KS', 'S', 'R'),
  ('Jeff', 'Merkley', 'OR', 'S', 'D'),
  ('Jeanne', 'Shaheen', 'NH', 'S', 'D'),
  ('Rob', 'Portman', 'OH', 'S', 'R'),
  ('Ron', 'Johnson', 'WI', 'S', 'R'),
  ('Ron', 'Wyden', 'OR', 'S', 'D'),
  ('Jeff', 'Flake', 'AZ', 'S', 'R'),
  ('Tina', 'Smith', 'MN', 'S', 'D'),
  ('Susan', 'Collins', 'ME', 'S', 'R'),
  ('Cory', 'Gardner', 'CO', 'S', 'R'),
  ('Tom', 'Cotton', 'AR', 'S', 'R'),
  ('Christopher', 'S. Murphy', 'CT', 'S', 'D'),
  ('Tom', 'Carper', 'DE', 'S', 'D'),
  ('Bill', 'Nelson', 'FL', 'S', 'D'),
  ('Mazie', 'K. Hirono', 'HI', 'S', 'D'),
  ('Joe', 'Donnelly', 'IN', 'S', 'D'),
  ('Angus', 'King', 'ME', 'S', 'I'),
  ('Tom', 'Udall', 'NM', 'S', 'D'),
  ('Debbie', 'Stabenow', 'MI', 'S', 'D'),
  ('Amy', 'Klobuchar', 'MN', 'S', 'D'),
  ('Claire', 'McCaskill', 'MO', 'S', 'D'),
  ('Dean', 'Heller', 'NV', 'S', 'R'),
  ('Martin', 'Heinrich', 'NM', 'S', 'D'),
  ('Kirsten', 'Gillibrand', 'NY', 'S', 'D'),
  ('Heidi', 'Heitkamp', 'ND', 'S', 'D'),
  ('Bob', 'Casey Jr.', 'PA', 'S', 'D'),
  ('Ted', 'Cruz', 'TX', 'S', 'R'),
  ('Bernie', 'Sanders', 'VT', 'S', 'I'),
  ('Maria', 'Cantwell', 'WA', 'S', 'D'),
  ('Tammy', 'Baldwin', 'WI', 'S', 'D'),
  ('John', 'Barrasso', 'WY', 'S', 'R'),
  ('Mike', 'Lee', 'UT', 'S', 'R'),
  ('Ben', 'Cardin', 'MD', 'S', 'D'),
  ('John', 'Cornyn', 'TX', 'S', 'R'),
  ('Deb', 'Fischer', 'NE', 'S', 'R'),
  ('Dianne', 'Feinstein', 'CA', 'S', 'D'),
  ('Roy', 'Blunt', 'MO', 'S', 'R'),
  ('Jon', 'Tester', 'MT', 'S', 'D'),
  ('Mitch', 'McConnell', 'KY', 'S', 'R'),
  ('John', 'McCain', 'AZ', 'S', 'R'),
  ('John', 'Boozman', 'AR', 'S', 'R'),
  ('Mike', 'Enzi', 'WY', 'S', 'R'),
  ('Mike', 'Crapo', 'ID', 'S', 'R'),
  ('Roger', 'Wicker', 'MI', 'S', 'R'),
  ('Joni', 'Ernst', 'IA', 'S', 'R'),
  ('Sherrod', 'Brown', 'OH', 'S', 'D'),
  ('Cory', 'Booker', 'NJ', 'S', 'D'),
  ('Kamala', 'D. Harris', 'CA', 'S', 'D'),
  ('Catherine', 'Cortez Masto', 'NV', 'S', 'D'),
  ('John', 'Thune', 'SD', 'S', 'R'),
  ('Elizabeth', 'Warren', 'MA', 'S', 'D'),
  ('Jim', 'Risch', 'ID', 'S', 'R'),
  ('John', 'Hoeven', 'ND', 'S', 'R'),
  ('Tim', 'Kaine', 'VA', 'S', 'D'),
  ('Joe', 'Manchin III', 'WV', 'S', 'D'),
  ('Mike', 'Rounds', 'SD', 'S', 'R'),
  ('Johnny', 'Isakson', 'GA', 'S', 'R'),
  ('Marco', 'Rubio', 'FL', 'S', 'R'),
  ('Patrick', 'Leahy', 'VT', 'S', 'D'),
  ('Richard', 'Shelby', 'AL', 'S', 'R'),
  ('Ed', 'Markey', 'MA', 'S', 'D'),
  ('Lisa', 'Murkowski', 'AK', 'S', 'R'),
  ('Richard', 'Blumenthal', 'CT', 'S', 'D'),
  ('Rand', 'Paul', 'KY', 'S', 'R'),
  ('Tim', 'Scott', 'SC', 'S', 'R'),
  ('Sheldon', 'Whitehouse', 'RI', 'S', 'D'),
  ('James', 'Lankford', 'OK', 'S', 'R'),
  ('Patty', 'Murray', 'WA', 'S', 'D'),
  ('Cindy', 'Hyde-Smith', 'MI', 'S', 'R'),

  ('Vicente', 'González', 'TX', 'H', 'D'),
  ('Gene', 'Green', 'TX', 'H', 'D'),
  ('Ileana', 'Ros-Lehtinen', 'FL', 'H', 'R'),
  ('Raul', 'Labrador', 'ID', 'H', 'R'),
  ('Sam', 'Johnson', 'TX', 'H', 'R'),
  ('Ralph', 'Norman', 'SC', 'H', 'R'),
  ('Charles', 'W. Dent', 'PA', 'H', 'R'),
  ('Sandy', 'Levin', 'MI', 'H', 'D'),
  ('Jim', 'Bridenstine', 'OK', 'H', 'R'),
  ('Ruben', 'J. Kihuen', 'NV', 'H', 'D'),
  ('Carol', 'Shea-Porter', 'NH', 'H', 'D'),
  ('Dave', 'Reichert', 'WA', 'H', 'R'),
  ('Jeb', 'Hensarling', 'TX', 'H', 'R'),
  ('Bill', 'Shuster', 'PA', 'H', 'R'),
  ('John', 'Curtis', 'UT', 'H', 'R'),
  ('Ron', 'Estes', 'KS', 'H', 'R'),
  ('Edward', 'Royce', 'CA', 'H', 'R'),
  ('David', 'Trott', 'MI', 'H', 'R'),
  ('Diane', 'Black', 'TN', 'H', 'R'),
  ('Luis', 'V. Gutierrez', 'IL', 'H', 'D'),
  ('Kristi', 'L. Noem', 'SD', 'H', 'R'),
  ('Gwen', 'Moore', 'WI', 'H', 'D'),
  ('Markwayne', 'Mullin', 'OK', 'H', 'R'),
  ('Jared', 'Polis', 'CO', 'H', 'D'),
  ('Steve', 'Pearce', 'NM', 'H', 'R'),
  ('Luke', 'Messer', 'IN', 'H', 'R'),
  ('Jim', 'Renacci', 'OH', 'H', 'R'),
  ('Lou', 'Barletta', 'PA', 'H', 'R'),
  ('Marsha', 'Blackburn', 'TN', 'H', 'R'),
  ('Mike', 'Rogers', 'AL', 'H', 'R'),
  ('Don', 'Young', 'AK', 'H', 'R'),
  ('Andy', 'Biggs', 'AZ', 'H', 'R'),
  ('Rick', 'Crawford', 'AR', 'H', 'R'),
  ('David', 'G. Valadao', 'CA', 'H', 'R'),
  ('Kevin', 'McCarthy', 'CA', 'H', 'R'),
  ('Mike', 'Thompson', 'CA', 'H', 'D'),
  ('Paul', 'Cook', 'CA', 'H', 'R'),
  ('Scott', 'Peters', 'CA', 'H', 'D'),
  ('Zoe', 'Lofgren', 'CA', 'H', 'D'),
  ('Gregg', 'Harper', 'MS', 'H', 'R'),
  ('Jacky', 'Rosen', 'NV', 'H', 'D'),
  ('Colleen', 'Hanabusa', 'HI', 'H', 'D'),
  ('Frederica', 'S. Wilson', 'FL', 'H', 'D'),
  ('John', 'J. Duncan, Jr.', 'TN', 'H', 'R'),
  ('Adam', 'Schiff', 'CA', 'H', 'D'),
  ('Alan', 'Lowenthal', 'CA', 'H', 'D'),
  ('Ami', 'Bera', 'CA', 'H', 'D'),
  ('Anna', 'Eshoo', 'CA', 'H', 'D'),
  ('Barbara', 'Lee', 'CA', 'H', 'D'),
  ('Brad', 'Sherman', 'CA', 'H', 'D'),
  ('Bradley', 'Byrne', 'AL', 'H', 'R'),
  ('Bruce', 'Westerman', 'AR', 'H', 'R'),
  ('Dana', 'Rohrabacher', 'CA', 'H', 'R'),
  ('Sanford', 'Bishop, Jr', 'GA', 'H', 'D'),
  ('David', 'Schweikert', 'AZ', 'H', 'R'),
  ('Devin', 'Nunes', 'CA', 'H', 'R'),
  ('Diana', 'DeGette', 'CO', 'H', 'D'),
  ('Patrick', 'Meehan', 'PA', 'H', 'R'),
  ('Alfred', 'Lawson', 'FL', 'H', 'D'),
  ('Austin', 'Scott', 'GA', 'H', 'R'),
  ('Doris', 'Matsui', 'CA', 'H', 'D'),
  ('Adam', 'Kinzinger', 'IL', 'H', 'R'),
  ('Barry', 'Loudermilk', 'GA', 'H', 'R'),
  ('Doug', 'LaMalfa', 'CA', 'H', 'R'),
  ('Doug', 'Lamborn', 'CO', 'H', 'R'),
  ('Duncan', 'Hunter', 'CA', 'H', 'R'),
  ('Ed', 'Perlmutter', 'CO', 'H', 'D'),
  ('Bill', 'Foster', 'IL', 'H', 'D'),
  ('Bill', 'Posey', 'FL', 'H', 'R'),
  ('Eric', 'Swalwell', 'CA', 'H', 'D'),
  ('Evan', 'Jenkins', 'WV', 'H', 'R'),
  ('French', 'Hill', 'AR', 'H', 'R'),
  ('Michelle', 'Lujan Grisham', 'NM', 'H', 'D'),
  ('Gary', 'Palmer', 'AL', 'H', 'R'),
  ('Grace', 'Napolitano', 'CA', 'H', 'D'),
  ('Carlos', 'Curbelo', 'FL', 'H', 'R'),
  ('Cheri', 'Bustos', 'IL', 'H', 'D'),
  ('Daniel', 'Lipinski', 'IL', 'H', 'D'),
  ('Andre', 'Carson', 'IN', 'H', 'D'),
  ('Jackie', 'Speier', 'CA', 'H', 'D'),
  ('Jared', 'Huffman', 'CA', 'H', 'D'),
  ('Darin', 'LaHood', 'IL', 'H', 'R'),
  ('Jeff', 'Denham', 'CA', 'H', 'R'),
  ('Darren', 'Soto', 'FL', 'H', 'D'),
  ('Jerry', 'McNerney', 'CA', 'H', 'D'),
  ('Jim', 'Costa', 'CA', 'H', 'D'),
  ('Debbie', 'Wasserman Schultz', 'FL', 'H', 'D'),
  ('Jimmy', 'Gomez', 'CA', 'H', 'D'),
  ('Jimmy', 'Panetta', 'CA', 'H', 'D'),
  ('Doug', 'Collins', 'GA', 'H', 'R'),
  ('Drew', 'Ferguson', 'GA', 'H', 'R'),
  ('Earl', '\"Buddy\" Carter', 'GA', 'H', 'R'),
  ('Elizabeth', 'Esty', 'CT', 'H', 'D'),
  ('Juan', 'Vargas', 'CA', 'H', 'D'),
  ('Judy', 'Chu', 'CA', 'H', 'D'),
  ('Julia', 'Brownley', 'CA', 'H', 'D'),
  ('Karen', 'Bass', 'CA', 'H', 'D'),
  ('Ken', 'Buck', 'CO', 'H', 'R'),
  ('Ken', 'Calvert', 'CA', 'H', 'R'),
  ('Hank', 'Johnson', 'GA', 'H', 'D'),
  ('Jackie', 'Walorski', 'IN', 'H', 'R'),
  ('Linda', 'Sanchez', 'CA', 'H', 'D'),
  ('Lou', 'Correa', 'CA', 'H', 'D'),
  ('Jim', 'Himes', 'CT', 'H', 'D'),
  ('Lucille', 'Roybal-Allard', 'CA', 'H', 'D'),
  ('Mark', 'DeSaulnier', 'CA', 'H', 'D'),
  ('Mark', 'Takano', 'CA', 'H', 'D'),
  ('Jody', 'Hice', 'GA', 'H', 'R'),
  ('Joe', 'Courtney', 'CT', 'H', 'D'),
  ('John', 'Rutherford', 'FL', 'H', 'R'),
  ('Martha', 'Roby', 'AL', 'H', 'R'),
  ('John', 'Shimkus', 'IL', 'H', 'R'),
  ('Maxine', 'Waters', 'CA', 'H', 'D'),
  ('Mimi', 'Walters', 'CA', 'H', 'R'),
  ('Mo', 'Brooks', 'AL', 'H', 'R'),
  ('Nancy', 'Pelosi', 'CA', 'H', 'D'),
  ('Nanette', 'Barragan', 'CA', 'H', 'D'),
  ('Norma', 'Torres', 'CA', 'H', 'D'),
  ('Kathy', 'Castor', 'FL', 'H', 'D'),
  ('Paul', 'Gosar', 'AZ', 'H', 'R'),
  ('Pete', 'Aguilar', 'CA', 'H', 'D'),
  ('Larry', 'Bucshon', 'IN', 'H', 'R'),
  ('Lois', 'Frankel', 'FL', 'H', 'D'),
  ('Raul', 'Grijalva', 'AZ', 'H', 'D'),
  ('Raul', 'Ruiz', 'CA', 'H', 'D'),
  ('Mario', 'Diaz-Balart', 'FL', 'H', 'R'),
  ('Ro', 'Khanna', 'CA', 'H', 'D'),
  ('Matt', 'Gaetz', 'FL', 'H', 'R'),
  ('Robert', 'Aderholt', 'AL', 'H', 'R'),
  ('Neal', 'Dunn', 'FL', 'H', 'R'),
  ('Ruben', 'Gallego', 'AZ', 'H', 'D'),
  ('Salud', 'Carbajal', 'CA', 'H', 'D'),
  ('Randy', 'Hultgren', 'IL', 'H', 'R'),
  ('Mike', 'Quigley', 'IL', 'H', 'D'),
  ('Rick', 'Allen', 'GA', 'H', 'R'),
  ('Rob', 'Woodall', 'GA', 'H', 'R'),
  ('Robin', 'Kelly', 'IL', 'H', 'D'),
  ('John', 'Delaney', 'MD', 'H', 'D'),
  ('John', 'Larson', 'CT', 'H', 'D'),
  ('Danny', 'K. Davis', 'IL', 'H', 'D'),
  ('Jan', 'Schakowsky', 'IL', 'H', 'D'),
  ('Raja', 'Krishnamoorthi', 'IL', 'H', 'D'),
  ('Brad', 'Schneider', 'IL', 'H', 'D'),
  ('Andy', 'Barr', 'KY', 'H', 'R'),
  ('Scott', 'Tipton', 'CO', 'H', 'R'),
  ('Stephen', 'Knight', 'CA', 'H', 'R'),
  ('Dave', 'Loebsack', 'IA', 'H', 'D'),
  ('Stephanie', 'Murphy', 'FL', 'H', 'D'),
  ('Rod', 'Blum', 'IA', 'H', 'R'),
  ('Steve', 'Womack', 'AR', 'H', 'R'),
  ('Lynn', 'Jenkins', 'KS', 'H', 'R'),
  ('Susan', 'Brooks', 'IN', 'H', 'R'),
  ('Roger', 'Marshall', 'KS', 'H', 'R'),
  ('Brett', 'Guthrie', 'KY', 'H', 'R'),
  ('Hal', 'Rogers', 'KY', 'H', 'R'),
  ('Susan', 'Davis', 'CA', 'H', 'D'),
  ('Ted', 'Lieu', 'CA', 'H', 'D'),
  ('James', 'Comer Jr.', 'KY', 'H', 'R'),
  ('Terri', 'Sewell', 'AL', 'H', 'D'),
  ('Ted', 'Yoho', 'FL', 'H', 'R'),
  ('Thomas', 'Massie', 'KY', 'H', 'R'),
  ('Tom', 'Graves', 'GA', 'H', 'R'),
  ('Bruce', 'Poliquin', 'ME', 'H', 'R'),
  ('Tom', 'McClintock', 'CA', 'H', 'R'),
  ('Chellie', 'Pingree', 'ME', 'H', 'D'),
  ('Tom', 'O''Halleran', 'AZ', 'H', 'D'),
  ('Joe', 'Barton', 'TX', 'H', 'R'),
  ('Tony', 'Cardenas', 'CA', 'H', 'D'),
  ('Dutch', 'Ruppersberger', 'MD', 'H', 'D'),
  ('Tulsi', 'Gabbard', 'HI', 'H', 'D'),
  ('Val', 'Demings', 'FL', 'H', 'D'),
  ('Vern', 'Buchanan', 'FL', 'H', 'R'),
  ('Elijah', 'Cummings', 'MD', 'H', 'D'),
  ('John', 'Sarbanes', 'MD', 'H', 'D'),
  ('Bill', 'Keating', 'MA', 'H', 'D'),
  ('Joseph', 'Kennedy III', 'MA', 'H', 'D'),
  ('Katherine', 'Clark', 'MA', 'H', 'D'),
  ('Michael', 'Capuano', 'MA', 'H', 'D'),
  ('Richard', 'Neal', 'MA', 'H', 'D'),
  ('Seth', 'Moulton', 'MA', 'H', 'D'),
  ('Stephen', 'Lynch', 'MA', 'H', 'D'),
  ('Bill', 'Huizenga', 'MI', 'H', 'R'),
  ('Brenda', 'Lawrence', 'MI', 'H', 'D'),
  ('Dan', 'Kildee', 'MI', 'H', 'D'),
  ('Debbie', 'Dingell', 'MI', 'H', 'D'),
  ('Fred', 'Upton', 'MI', 'H', 'R'),
  ('Jack', 'Bergman', 'MI', 'H', 'R'),
  ('John', 'Moolenaar', 'MI', 'H', 'R'),
  ('Justin', 'Amash', 'MI', 'H', 'R'),
  ('Tim', 'Walberg', 'MI', 'H', 'R'),
  ('Betty', 'McCollum', 'MN', 'H', 'D'),
  ('Collin', 'Peterson', 'MN', 'H', 'D'),
  ('Rick', 'Nolan', 'MN', 'H', 'D'),
  ('Tom', 'Emmer', 'MN', 'H', 'R'),
  ('Bennie', 'Thompson', 'MS', 'H', 'D'),
  ('Steven', 'Palazzo', 'MS', 'H', 'R'),
  ('Trent', 'Kelly', 'MS', 'H', 'R'),
  ('Ann', 'Wagner', 'MO', 'H', 'R'),
  ('Billy', 'Long', 'MO', 'H', 'R'),
  ('Blaine', 'Luetkemeyer', 'MO', 'H', 'R'),
  ('Emanuel', 'Cleaver', 'MO', 'H', 'D'),
  ('Sam', 'Graves', 'MO', 'H', 'R'),
  ('William', 'Lacy Clay', 'MO', 'H', 'D'),
  ('Greg', 'Gianforte', 'MT', 'H', 'R'),
  ('Adrian', 'Smith', 'NE', 'H', 'R'),
  ('Don', 'Bacon', 'NE', 'H', 'R'),
  ('Dina', 'Titus', 'NV', 'H', 'D'),
  ('Mark', 'Amodei', 'NV', 'H', 'R'),
  ('Albio', 'Sires', 'NJ', 'H', 'D'),
  ('Bill', 'Pascrell', 'NJ', 'H', 'D'),
  ('Bonnie', 'Watson Coleman', 'NJ', 'H', 'D'),
  ('Donald', 'Norcross', 'NJ', 'H', 'D'),
  ('Donald', 'Payne, Jr.', 'NJ', 'H', 'D'),
  ('Frank', 'Pallone', 'NJ', 'H', 'D'),
  ('Josh', 'Gottheimer', 'NJ', 'H', 'D'),
  ('Leonard', 'Lance', 'NJ', 'H', 'R'),
  ('Rodney', 'Frelinghuysen', 'NJ', 'H', 'R'),
  ('Tom', 'MacArthur', 'NJ', 'H', 'R'),
  ('Ben', 'Ray Lujan', 'NM', 'H', 'D'),
  ('Adriano', 'Espaillat', 'NY', 'H', 'D'),
  ('Brian', 'Higgins', 'NY', 'H', 'D'),
  ('Eliot', 'Engel', 'NY', 'H', 'D'),
  ('Elise', 'Stefanik', 'NY', 'H', 'R'),
  ('Grace', 'Meng', 'NY', 'H', 'D'),
  ('Gregory', 'W. Meeks', 'NY', 'H', 'D'),
  ('Hakeem', 'Jeffries', 'NY', 'H', 'D'),
  ('John', 'Faso', 'NY', 'H', 'R'),
  ('John', 'Katko', 'NY', 'H', 'R'),
  ('Joseph', 'Crowley', 'NY', 'H', 'D'),
  ('Lee', 'Zeldin', 'NY', 'H', 'R'),
  ('Nita', 'Lowey', 'NY', 'H', 'D'),
  ('Nydia', 'Velazquez', 'NY', 'H', 'D'),
  ('Paul', 'Tonko', 'NY', 'H', 'D'),
  ('Sean', 'Maloney', 'NY', 'H', 'D'),
  ('Tom', 'Reed', 'NY', 'H', 'R'),
  ('David', 'Price', 'NC', 'H', 'D'),
  ('David', 'Rouzer', 'NC', 'H', 'R'),
  ('G', 'K. Butterfield', 'NC', 'H', 'D'),
  ('Patrick', 'T. McHenry', 'NC', 'H', 'R'),
  ('Richard', 'Hudson', 'NC', 'H', 'R'),
  ('Robert', 'Pittenger', 'NC', 'H', 'R'),
  ('Ted', 'Budd', 'NC', 'H', 'R'),
  ('Kevin', 'Cramer', 'ND', 'H', 'R'),
  ('Bob', 'Gibbs', 'OH', 'H', 'R'),
  ('Brad', 'Wenstrup', 'OH', 'H', 'R'),
  ('David', 'Joyce', 'OH', 'H', 'R'),
  ('Jerrold', 'Nadler', 'NY', 'H', 'D'),
  ('Beto', 'O''Rourke', 'TX', 'H', 'D'),
  ('Joyce', 'Beatty', 'OH', 'H', 'D'),
  ('Marcy', 'Kaptur', 'OH', 'H', 'D'),
  ('Steve', 'Chabot', 'OH', 'H', 'R'),
  ('Steve', 'Stivers', 'OH', 'H', 'R'),
  ('Frank', 'D. Lucas', 'OK', 'H', 'R'),
  ('Steve', 'Russell', 'OK', 'H', 'R'),
  ('Earl', 'Blumenauer', 'OR', 'H', 'D'),
  ('Greg', 'Walden', 'OR', 'H', 'R'),
  ('Kurt', 'Schrader', 'OR', 'H', 'D'),
  ('Peter', 'DeFazio', 'OR', 'H', 'D'),
  ('Suzanne', 'Bonamici', 'OR', 'H', 'D'),
  ('Brendan', 'Boyle', 'PA', 'H', 'D'),
  ('Brian', 'Fitzpatrick', 'PA', 'H', 'R'),
  ('Dwight', 'Evans', 'PA', 'H', 'D'),
  ('Glenn', 'Thompson', 'PA', 'H', 'R'),
  ('Keith', 'Rothfus', 'PA', 'H', 'R'),
  ('Matt', 'Cartwright', 'PA', 'H', 'D'),
  ('Robert', 'Brady', 'PA', 'H', 'D'),
  ('Ryan', 'Costello', 'PA', 'H', 'R'),
  ('Scott', 'Perry', 'PA', 'H', 'R'),
  ('Tom', 'Marino', 'PA', 'H', 'R'),
  ('Trey', 'Gowdy', 'SC', 'H', 'R'),
  ('David', 'Kustoff', 'TN', 'H', 'R'),
  ('Phil', 'Roe', 'TN', 'H', 'R'),
  ('Steve', 'Cohen', 'TN', 'H', 'D'),
  ('Al', 'Green', 'TX', 'H', 'D'),
  ('Bill', 'Flores', 'TX', 'H', 'R'),
  ('Brian', 'Babin', 'TX', 'H', 'R'),
  ('Eddie', 'Bernice Johnson', 'TX', 'H', 'D'),
  ('Henry', 'Cuellar', 'TX', 'H', 'D'),
  ('Joaquin', 'Castro', 'TX', 'H', 'D'),
  ('Jodey', 'Arrington', 'TX', 'H', 'R'),
  ('John', 'Carter', 'TX', 'H', 'R'),
  ('John', 'Culberson', 'TX', 'H', 'R'),
  ('John', 'Ratcliffe', 'TX', 'H', 'R'),
  ('Kay', 'Granger', 'TX', 'H', 'R'),
  ('Kenny', 'Marchant', 'TX', 'H', 'R'),
  ('Kevin', 'Brady', 'TX', 'H', 'R'),
  ('Lloyd', 'Doggett', 'TX', 'H', 'D'),
  ('Mac', 'Thornberry', 'TX', 'H', 'R'),
  ('Marc', 'Veasey', 'TX', 'H', 'D'),
  ('Michael', 'McCaul', 'TX', 'H', 'R'),
  ('Pete', 'Olson', 'TX', 'H', 'R'),
  ('Pete', 'Sessions', 'TX', 'H', 'R'),
  ('Randy', 'Weber', 'TX', 'H', 'R'),
  ('Sheila', 'Jackson Lee', 'TX', 'H', 'D'),
  ('Will', 'Hurd', 'TX', 'H', 'R'),
  ('Mia', 'Love', 'UT', 'H', 'R'),
  ('Rob', 'Bishop', 'UT', 'H', 'R'),
  ('Peter', 'Welch', 'VT', 'H', 'D'),
  ('Barbara', 'Comstock', 'VA', 'H', 'R'),
  ('David', 'Brat', 'VA', 'H', 'R'),
  ('Don', 'Beyer', 'VA', 'H', 'D'),
  ('Morgan', 'Griffith', 'VA', 'H', 'R'),
  ('Rob', 'Wittman', 'VA', 'H', 'R'),
  ('Cathy', 'McMorris Rodgers', 'WA', 'H', 'R'),
  ('Dan', 'Newhouse', 'WA', 'H', 'R'),
  ('Denny', 'Heck', 'WA', 'H', 'D'),
  ('Jaime', 'Herrera Beutler', 'WA', 'H', 'R'),
  ('Rick', 'Larsen', 'WA', 'H', 'D'),
  ('Suzan', 'DelBene', 'WA', 'H', 'D'),
  ('Alexander', 'Mooney', 'WV', 'H', 'R'),
  ('David', 'McKinley', 'WV', 'H', 'R'),
  ('Glenn', 'Grothman', 'WI', 'H', 'R'),
  ('Jim', 'Sensenbrenner', 'WI', 'H', 'R'),
  ('Mark', 'Pocan', 'WI', 'H', 'D'),
  ('Paul', 'Ryan', 'WI', 'H', 'R'),
  ('Ron', 'Kind', 'WI', 'H', 'D'),
  ('Sean', 'Duffy', 'WI', 'H', 'R'),
  ('Liz', 'Cheney', 'WY', 'H', 'R'),
  ('Adam', 'Smith', 'WA', 'H', 'D'),
  ('Alcee', 'L. Hastings', 'FL', 'H', 'D'),
  ('Andy', 'Harris', 'MD', 'H', 'R'),
  ('Bill', 'Johnson', 'OH', 'H', 'R'),
  ('Bob', 'Latta', 'OH', 'H', 'R'),
  ('Bobby', 'Rush', 'IL', 'H', 'D'),
  ('Bobby', 'Scott', 'VA', 'H', 'D'),
  ('Carolyn', 'B. Maloney', 'NY', 'H', 'D'),
  ('Charles', 'J. Fleischmann', 'TN', 'H', 'R'),
  ('Chris', 'Collins', 'NY', 'H', 'R'),
  ('Chris', 'Smith', 'NJ', 'H', 'R'),
  ('Chris', 'Stewart', 'UT', 'H', 'R'),
  ('Daniel', 'Donovan', 'NY', 'H', 'R'),
  ('Daniel', 'Webster', 'FL', 'H', 'R'),
  ('David', 'Scott', 'GA', 'H', 'D'),
  ('David', 'Young', 'IA', 'H', 'R'),
  ('Brian', 'Mast', 'FL', 'H', 'R'),
  ('Dennis', 'A. Ross', 'FL', 'H', 'R'),
  ('Filemon', 'Vela', 'TX', 'H', 'D'),
  ('Paul', 'Mitchell', 'MI', 'H', 'R'),
  ('Gerry', 'Connolly', 'VA', 'H', 'D'),
  ('Karen', 'Handel', 'GA', 'H', 'R'),
  ('Todd', 'Rokita', 'IN', 'H', 'R'),
  ('Gus', 'M. Bilirakis', 'FL', 'H', 'R'),
  ('James', 'Clyburn', 'SC', 'H', 'D'),
  ('Jason', 'Lewis', 'MN', 'H', 'R'),
  ('Jason', 'Smith', 'MO', 'H', 'R'),
  ('Erik', 'Paulsen', 'MN', 'H', 'R'),
  ('Jeff', 'Duncan', 'SC', 'H', 'R'),
  ('Darrell', 'Issa', 'CA', 'H', 'R'),
  ('Jeffrey', 'Fortenberry', 'NE', 'H', 'R'),
  ('Jim', 'Cooper', 'TN', 'H', 'D'),
  ('Jim', 'Jordan', 'OH', 'H', 'R'),
  ('Jim', 'McGovern', 'MA', 'H', 'D'),
  ('Joe', 'Wilson', 'SC', 'H', 'R'),
  ('Clay', 'Higgins', 'LA', 'H', 'R'),
  ('John', 'Lewis', 'GA', 'H', 'D'),
  ('Francis', 'Rooney', 'FL', 'H', 'R'),
  ('José', 'E. Serrano', 'NY', 'H', 'D'),
  ('Keith', 'Ellison', 'MN', 'H', 'D'),
  ('Louis', 'B. \"Louie\" Gohmert Jr.', 'TX', 'H', 'R'),
  ('Mark', 'Meadows', 'NC', 'H', 'R'),
  ('Mark', 'Sanford', 'SC', 'H', 'R'),
  ('Mike', 'Bishop', 'MI', 'H', 'R'),
  ('Michael', 'C. Burgess', 'TX', 'H', 'R'),
  ('Kyrsten', 'Sinema', 'AZ', 'H', 'D'),
  ('Kevin', 'Yoder', 'KS', 'H', 'R'),
  ('Michael', 'F. Doyle', 'PA', 'H', 'D'),
  ('Mike', 'Gallagher', 'WI', 'H', 'R'),
  ('Michael', 'K. Simpson', 'ID', 'H', 'R'),
  ('Derek', 'Kilmer', 'WA', 'H', 'D'),
  ('Michael', 'Turner', 'OH', 'H', 'R'),
  ('Mike', 'Coffman', 'CO', 'H', 'R'),
  ('Mike', 'Conaway', 'TX', 'H', 'R'),
  ('Mike', 'Kelly', 'PA', 'H', 'R'),
  ('Peter', 'T. King', 'NY', 'H', 'R'),
  ('Peter', 'J. Roskam', 'IL', 'H', 'R'),
  ('Rodney', 'Davis', 'IL', 'H', 'R'),
  ('Roger', 'Williams', 'TX', 'H', 'R'),
  ('Rosa', 'L. DeLauro', 'CT', 'H', 'D'),
  ('Steve', 'King', 'IA', 'H', 'R'),
  ('Theodore', 'E. Deutch', 'FL', 'H', 'D'),
  ('Tim', 'Ryan', 'OH', 'H', 'D'),
  ('Tom', 'Rice', 'SC', 'H', 'R'),
  ('Mike', 'Bost', 'IL', 'H', 'R'),
  ('Walter', 'B. Jones', 'NC', 'H', 'R'),
  ('Yvette', 'D. Clarke', 'NY', 'H', 'D'),
  ('Annie', 'Kuster', 'NH', 'H', 'D'),
  ('Cedric', 'Richmond', 'LA', 'H', 'D'),
  ('Claudia', 'Tenney', 'NY', 'H', 'R'),
  ('David', 'N. Cicilline', 'RI', 'H', 'D'),
  ('Donald', 'McEachin', 'VA', 'H', 'D'),
  ('Garret', 'Graves', 'LA', 'H', 'R'),
  ('Jamie', 'Raskin', 'MD', 'H', 'D'),
  ('Jim', 'Banks', 'IN', 'H', 'R'),
  ('Jim', 'Langevin', 'RI', 'H', 'D'),
  ('Charlie', 'Crist', 'FL', 'H', 'D'),
  ('Anthony', 'G. Brown', 'MD', 'H', 'D'),
  ('Lisa', 'Blunt Rochester', 'DE', 'H', 'D'),
  ('Lloyd', 'Smucker', 'PA', 'H', 'R'),
  ('Mike', 'Johnson', 'LA', 'H', 'R'),
  ('Pramila', 'Jayapal', 'WA', 'H', 'D'),
  ('Ralph', 'Abraham', 'LA', 'H', 'R'),
  ('Scott', 'Taylor', 'VA', 'H', 'R'),
  ('Steve', 'Scalise', 'LA', 'H', 'R'),
  ('Thomas', 'Garrett', 'VA', 'H', 'R'),
  ('John', 'A. Yarmuth', 'KY', 'H', 'D'),
  ('Martha', 'McSally', 'AZ', 'H', 'R'),
  ('John', 'Garamendi', 'CA', 'H', 'D'),
  ('Bob', 'Goodlatte', 'VA', 'H', 'R'),
  ('Kathleen', 'M. Rice', 'NY', 'H', 'D'),
  ('Frank', 'LoBiondo', 'NJ', 'H', 'R'),
  ('Tim', 'Walz', 'MN', 'H', 'D'),
  ('Tom', 'Suozzi', 'NY', 'H', 'D'),
  ('George', 'E.B. Holding', 'NC', 'H', 'R'),
  ('Marcia', 'Fudge', 'OH', 'H', 'D'),
  ('Alma', 'Adams', 'NC', 'H', 'D'),
  ('Peter', 'Visclosky', 'IN', 'H', 'D'),
  ('Scott', 'DesJarlais', 'TN', 'H', 'R'),
  ('Steny', 'Hoyer', 'MD', 'H', 'D'),
  ('Thomas', 'J. Rooney', 'FL', 'H', 'R'),
  ('Tom', 'Cole', 'OK', 'H', 'R'),
  ('Trey', 'Hollingsworth', 'IN', 'H', 'R'),
  ('Lamar', 'Smith', 'TX', 'H', 'R'),
  ('Mark', 'Walker', 'NC', 'H', 'R'),
  ('Vicky', 'Hartzler', 'MO', 'H', 'R'),
  ('Virginia', 'Foxx', 'NC', 'H', 'R'),
  ('Warren', 'Davidson', 'OH', 'H', 'R'),
  ('Ted', 'Poe', 'TX', 'H', 'R'),
  ('Ron', 'DeSantis', 'FL', 'H', 'R'),
  ('Niki', 'Tsongas', 'MA', 'H', 'D'),
  ('Conor', 'Lamb', 'PA', 'H', 'D')
").run_ignore_result

raise StandardError.new("Incorrect state data") if State.count != 50
raise StandardError.new("Incorrect representative data") if Representative.count != 530

superadmin = User.build 'hi@govpop.com', token: 'seeds'
superadmin.change_password_by_token 'seeds', 'supersecure'
superadmin.role = User::SUPERADMIN
superadmin.save!
Profile.create!(user: superadmin, state_id: 'OK')
session = superadmin.login! 'supersecure'
puts "curl -i -H \"Content-Type: application/json\" -H \"SSID: #{session.id}\" localhost:3003/"

r = Representative.first
q = Question.create!({
  creator: superadmin,
  voting_begins_at: Time.zone.now - 1.day,
  voting_ends_at: Time.zone.now + 5.day,
  title: "WWIII, Yay or Nay?",
  short_text: "Should we attack Syria?",
  full_text: "Blah blah blah Syria blah blah Russia blah Missiles blah Air Strikes",
  sponsors: [r]
})
puts "Q: #{q.reload.id}"
